language: c
compiler:
  - clang
  - gcc

env:
  - OPTIONS=-DCN_CBOR_USE_CONTEXT=OFF
  - OPTIONS=-DCN_CBOR_USE_CONTEXT=ON
  - OPTIONS=-DCN_CBOR_NO_FLOATS=ON
  - OPTIONS=-DCN_CBOR_ALIGN_READS=ON

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
script:
- "./build.sh all test"
